# Generated by Django 2.2.24 on 2022-12-20 20:36
import phonenumbers

from django.db import migrations


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        phonenumber = flat.owners_phonenumber
        for match in phonenumbers.PhoneNumberMatcher(phonenumber, "RU"):
            flat.owner_pure_phone = phonenumbers.format_number(
                match.number,
                phonenumbers.PhoneNumberFormat.E164
                )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
